import { imageSrcForTheme, type LandingTheme, type ThemedImageSource } from "./content";

interface ThemedPictureProps {
  image: ThemedImageSource;
  theme: LandingTheme;
  alt: string;
  width: number;
  height: number;
  loading?: "eager" | "lazy";
  decoding?: "async" | "auto" | "sync";
  fetchPriority?: "high" | "low" | "auto";
  className?: string;
}

/**
 * Theme-aware <picture> element that serves AVIF and WebP variants when the
 * browser supports them, falling back to the original PNG.
 *
 * Format negotiation:
 *   <source type="image/avif"> → <source type="image/webp"> → <img src=".png">
 *
 * Theme switching:
 *   Each source's srcSet is derived from the theme-aware PNG path by
 *   replacing the .png suffix with .avif or .webp. When the React theme
 *   state changes, all srcSet/src attributes re-render, so the browser
 *   re-selects the correct format + theme variant.
 *
 * The <img> retains width, height, loading, decoding, and fetchPriority so
 * the browser can reserve layout space and prioritize the LCP image before
 * the picture sources are resolved.
 *
 * AVIF and WebP files are generated by the project's image-optimization step
 * (cwebp + avifenc) and live alongside the PNGs in public/product/.
 */
export default function ThemedPicture({
  image,
  theme,
  alt,
  width,
  height,
  loading,
  decoding = "async",
  fetchPriority,
  className,
}: ThemedPictureProps) {
  const pngSrc = imageSrcForTheme(image, theme);
  const avifSrc = pngSrc.replace(/\.png$/, ".avif");
  const webpSrc = pngSrc.replace(/\.png$/, ".webp");

  return (
    <picture>
      <source type="image/avif" srcSet={avifSrc} />
      <source type="image/webp" srcSet={webpSrc} />
      <img
        src={pngSrc}
        alt={alt}
        width={width}
        height={height}
        loading={loading}
        decoding={decoding}
        fetchPriority={fetchPriority}
        className={className}
      />
    </picture>
  );
}
